image: ghcr.io/ionic-team/ionic-cli:6.11.11

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm ci
    - npm run test

test:
  stage: test
  script:
    - npm ci
    - npm run test

build-ios:
  stage: build
  script:
    - ionic package build ios ad-hoc --environment="GitLab" --native-config"=GitLab" --security-profile="GitLab" --target-platform="macOS - 2020.09" --build-file-name="GitLab-$CI_PIPELINE_ID.ipa"
  artifacts:
    paths:
      - GitLab-$CI_PIPELINE_ID.ipa
  only:
    - /^master$/

build-android:
  stage: build
  script:
    - ionic package build android debug --environment="GitLab" --native-config"=GitLab" --build-file-name="GitLab-$CI_PIPELINE_ID.apk"
  artifacts:
    paths:
      - GitLab-$CI_PIPELINE_ID.apk
  only:
    - /^master$/

build-live-update:
  stage: build
  script:
    - ionic deploy build --environment="Jenkins"
  only:
    - /^master$/