sudo: false

language: node_js
node_js:
  - '14.15.0'
before_install:
  - echo 'export const ENV = {parseAppId:"",parseJavascriptKey:"",parseServerUrl:"",parseMasterKey:"" }' > src/app/app.constant.ts
install:
  - npm install
  - npm install -g codecov

script:
  - npm ci --no-optional
  - npm run test:coverage
  - codecov
