name: Install, Lint, Build and Test
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Remove Node Modules
        uses: rm -rf node_modules
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        run: npm run test:ci
