name: Lint
on:
  push:
    branches:
      - refactor
      - main

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Run Lint
        run: npm run lint
