name: Build LIFE App and Deploy on Firebase
on:
  push:
    branches:
      - refactor
      - fix
      - feat
      - chore

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Run Tests
        run: npm run test