name: Teste Coverage
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Teste Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run test:coverage
