name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
      - feat-0000-add-user-registration-screen
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80 # optional parameter
